# Native Fpolicy blocking files
-
  name: Configure ONTAP
  hosts: localhost
  collections:
    - netapp.ontap
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: aggr1
    vol_name: vol01
    cifs_user: dougd
  tasks:
  - name: Export Create
    na_ontap_export_policy:
      state: present
      name: volume_policy
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Export Policy Rule Create
    na_ontap_export_policy_rule:
      state: present
      name: volume_policy
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      rule_index: 100
      ro_rule: any
      rw_rule: any
      protocol: cifs
      super_user_security: any
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Mod Default Policy
    na_ontap_export_policy_rule:
      state: present
      name: default
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      protocol: any
      rule_index: 100
      super_user_security: any
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: volume_policy
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      volume_security_style: ntfs
  - name: CIFS Share Create
    na_ontap_cifs:
      state: present
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      path: "/{{ vol_name }}"
      share_name: "{{ vol_name }}"
      https: true
      validate_certs: false
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "home"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: volume_policy
      junction_path: "/home"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      volume_security_style: ntfs
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "dbprod01"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: volume_policy
      junction_path: "/dbprod01"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      unix_permissions: 777
      volume_security_style: unix
  - name: CIFS Share Create
    na_ontap_cifs:
      state: present
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      path: "/dbprod01"
      share_name: "dbprod01"
      https: true
      validate_certs: false

  - name: Create FPolicy Event
    na_ontap_fpolicy_event:
      state: present
      vserver: "{{ vserver }}"
      name: fpolicy_event
      file_operations: ['create', 'create_dir', 'rename', 'rename_dir']
      protocol: cifs
      username: "{{ username }}"
      password: "{{ password }}"
      hostname: "{{ hostname }}"
      https: true
      validate_certs: false
  - name: Modify FPolicy policy
    na_ontap_fpolicy_policy:
      state: present
      vserver: "{{ vserver }}"
      name: fpolicy_policy
      events: fpolicy_event
      engine: native
      is_mandatory: false
      username: "{{ username }}"
      password: "{{ password }}"
      hostname: "{{ hostname }}"
      https: true
      validate_certs: false
  - name: Create FPolicy scope
    na_ontap_fpolicy_scope:
      state: present
      vserver: "{{ vserver }}"
      name: fpolicy_policy
      file_extensions_to_include: txt
      volumes_to_include: dbprod01
      username: "{{ username }}"
      password: "{{ password }}"
      hostname: "{{ hostname }}"
      https: true
      validate_certs: false
  - name: Enable fPolicy policy
    na_ontap_fpolicy_status:
      state: present
      vserver: "{{ vserver }}"
      policy_name: fpolicy_policy
      sequence_number: 10
      username: "{{ username }}"
      password: "{{ password }}"
      hostname: "{{ hostname }}"
      https: true
      validate_certs: false
