# CIFS AES required
-
  name: Configure ONTAP
  hosts: localhost
  collections:
    - netapp.ontap
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: cluster1_01_SSD_1
    vol_name: photoshop
    cifs_user: dougd
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: default
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      volume_security_style: ntfs
  - name: CIFS Share Create
    na_ontap_cifs:
      state: present
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      path: "/{{ vol_name }}"
      share_name: "{{ vol_name }}"
      https: true
      validate_certs: false
  - name: run ontap cli command
    netapp.ontap.na_ontap_rest_cli:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      command: 'vserver/cifs/security'
      verb: 'PATCH'
      params: {'vserver': 'svm1_cluster1', 'advertised-enc-types': 'des,rc4'}
      validate_certs: false
      https: true
-
  name: Set Up The Windows
  hosts: DC1.demo.netapp.com
  collections:
    - community.windows
    - anisble.windows   
    - microsoft.ad
  vars:
    hostname: 192.168.0.101
    username: DEMO\Administrator
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: aggr1
    vol_name: photoshop
  tasks:
  - name: Map Drive via PS
    ansible.windows.win_powershell:
     script: |
      New-SmbMapping -LocalPath 'X:' -RemotePath '\\192.168.0.131\photoshop' -UserName 'DEMO\Administrator' -Password 'Netapp1!';
      Set-AdUser -Identity dougd -HomeDirectory "\\192.168.0.131\photoshop"
  - name: set encryption types on cifs server
    microsoft.ad.computer:
      identity: cifs1$
      kerberos_encryption_types: ["aes128", "aes256"]
      enabled: yes
      state: present
