- 
  name: Configure ONTAP
  hosts: localhost
  collections:
    - netapp.ontap
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
  tasks:
  - name: Break Everything
    netapp.ontap.na_ontap_interface:
      state: absent
      interface_name: lif_svm1_cluster1_897
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: LMAO
    netapp.ontap.na_ontap_interface:
      state: absent
      interface_name: svm1_data_lif1
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: LMAO2
    netapp.ontap.na_ontap_interface:
      state: absent
      interface_name: svm1_data_lif2
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: EXPLOSIONS!!?!!
    netapp.ontap.na_ontap_svm:
      state: absent
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false