- 
  name: Build NIS Server
  hosts: localhost
  collections:
    - community.docker
  vars:
    nis_server: 192.168.0.4
  tasks:
  - name: Build the NIS server image
    ansible.builtin.command: "/usr/bin/docker build 
      https://raw.githubusercontent.com/nasteam/LOD-ansible/main/dockerfiles/nis/nis_dockerfile 
      -t nis"
  - name: Run the Docker NIS server
    ansible.builtin.command:   "/usr/bin/docker run
      -d -p 111:111 -p 111:111/udp -p 834-837:834-837 
      -p 834-837:834-837/udp 
      --hostname nis 
      --domainname demo.netapp.com 
      --privileged 
      -i -t nis 
      /bin/bash -c \"service rpcbind restart; service nis restart; tail -f /dev/null\""
- 
  name: Setup ONTAP NIS
  hosts: localhost
  collections:
    - netapp.ontap
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: aggr1
    vol_name: photoshop
    nis_server: 192.168.0.4
  tasks:
  - name: Export Create
    na_ontap_export_policy:
      state: present
      name: dbprod01_policy
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Mod Default Policy
    na_ontap_export_policy_rule:
      state: present
      name: default
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      protocol: any
      super_user_security: any
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false         
  - name: Export Policy Rule Create
    na_ontap_export_policy_rule:
      state: present
      name: dbprod01_policy
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: sys
      rw_rule: sys
      protocol: nfs
      super_user_security: sys
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: dbprod01_policy
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      unix_permissions: 777
      volume_security_style: unix
  - name: Configure NFS
    na_ontap_nfs:
      state: present
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vserver: "{{ vserver }}"
      nfsv41_pnfs: disabled
      nfsv41: enabled
      nfsv4: enabled
      nfsv4_id_domain: demo.netapp.local
      validate_certs: false
      https: true
  - name: Set ns-switch
    na_ontap_command:
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: no
      command: [ 'ns-switch', 'modify', '-vserver', "{{ vserver }}", '-database', 'passwd', '-sources', 'nis,files' ]
      privilege: 'admin'
-
  name: Set It Up For You
  hosts: centos01.demo.netapp.com
  collections:
    - ansible.posix
  tasks:
  - name: Mount Volume
    ansible.posix.mount:
      src: 192.168.0.131:/photoshop
      path: /mnt/photoshop_v3
      opts: vers=3,rw,sync,hard,intr,sec=sys
      boot: no
      state: mounted
      fstype: nfs
  - name: Mount Volume
    ansible.posix.mount:
      src: 192.168.0.131:/photoshop
      path: /mnt/photoshop_v4
      opts: vers=4,rw,sync,hard,intr,sec=sys
      boot: no
      state: mounted
      fstype: nfs
  - name: Add the user 'johnd' with a specific uid
    ansible.builtin.user:
      name: johnd
      comment: John Doe
      uid: 1003
  - name: Add the user 'ADB42F62' with a specific uid
    ansible.builtin.user:
      name: ADB42F62
      comment: John Doe
      uid: 1004
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /mnt/photoshop_v3/foo.conf
      state: touch
      owner: johnd
      group: johnd
      mode: '0644'
