-
  name: NFS04
  hosts: localhost
  collections:
    - netapp.ontap
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: aggr1
    vol_name: dbprod01
  tasks:
  - name: Export Create
    na_ontap_export_policy:
      state: present
      name: dbprod01_policy
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Mod Default Policy
    na_ontap_export_policy_rule:
      state: present
      name: default
      vserver: "{{ vserver }}"
      rule_index: 1
      client_match: 0.0.0.0/0
      ro_rule: sys
      rw_rule: sys
      protocol: nfs
      super_user_security: sys
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Export Policy Rule Create
    na_ontap_export_policy_rule:
      state: present
      name: dbprod01_policy
      vserver: "{{ vserver }}"
      rule_index: 1
      client_match: 0.0.0.0/0
      ro_rule: sys
      rw_rule: sys
      protocol: nfs
      super_user_security: sys
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: dbprod01_policy
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      unix_permissions: 777
      volume_security_style: unix
  - name: Configure NFS
    na_ontap_nfs:
      state: present
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vserver: "{{ vserver }}"
      nfsv41_pnfs: disabled
      nfsv41: enabled
      nfsv4: enabled
      nfsv4_id_domain: localdomain
      validate_certs: false
      https: true
-
  name: Set It Up For You
  debugger: on_failed
  hosts: centos01.demo.netapp.com
  collections:
    - ansible.posix
  tasks:
  - name: Mount Volume
    ansible.posix.mount:
      src: 192.168.0.131:/dbprod01
      path: /mnt/dbprod01
      opts: rw,sync,hard,intr,sec=sys
      boot: no
      state: mounted
      fstype: nfs
-
  name: Shutdown The Government
  hosts: localhost
  collections:
    - netapp.ontap
  tasks:
  - name: Tool We Will Need Later
    na_ontap_volume:
      state: present
      name: dbprod01
      vserver: svm1_cluster1
      hostname: 192.168.0.101
      username: admin
      password: Netapp1!
      junction_path: ''
      https: true
      validate_certs: false
  - name: The Tool
    na_ontap_volume:
      state: present
      name: dbprod01
      vserver: svm1_cluster1
      hostname: 192.168.0.101
      username: admin
      password: Netapp1!
      https: true
      validate_certs: false
      is_online: no
