- 
  name: Windows NFS Sucks
  hosts: localhost
  collections:
    - netapp.ontap
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: aggr1
    vol_name: photoshop
  tasks:
  - name: Export Create
    na_ontap_export_policy:
      state: present
      name: photoshop_policy
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Mod Default Policy
    na_ontap_export_policy_rule:
      state: present
      name: default
      vserver: "{{ vserver }}"
      rule_index: 1
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      protocol: any
      super_user_security: any
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false 
  - name: Export Policy Rule Create
    na_ontap_export_policy_rule:
      state: present
      name: photoshop_policy
      vserver: "{{ vserver }}"
      rule_index: 1
      client_match: 0.0.0.0,1.1.1.0/24
      ro_rule: sys
      rw_rule: sys
      protocol: nfs
      super_user_security: sys
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: photoshop_policy
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Service-Policy
    na_ontap_service_policy:
      state: present
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vserver: "{{ vserver }}"
      https: true
      validate_certs: false
      name: default_data_files
      services:
        - data_core
        - data_nfs
-
  name: Set Up Us The Windows
  hosts: DC1.demo.netapp.com
  collections:
    - community.windows
    - anisble.windows
  vars:
    hostname: 192.168.0.101
    username: DEMO\Administrator
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: aggr1
    vol_name: photoshop
  tasks:
  - name: Install NFS-Client
    win_feature:
      name: FS-NFS-Client
      state: present
