- 
  name: S3 Lab 3
  hosts: localhost
  collections:
    - netapp.ontap
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
    vol_name: s3_flexgroup
    bucket_name: svm1-bucket
    service_policy_name: default-data-files
    s3_server_name: s3_cluster1
  tasks:
  - name: create or modify s3 service
    na_ontap_s3_services:
      state: present
      name: "{{ s3_server_name }}"
      vserver: "{{ vserver }}"
      comment: not enabled
      enabled: True
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      use_rest: always
      validate_certs: false
  - name: create or modify s3 user
    na_ontap_s3_users:
      state: present
      name: user1
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      use_rest: always
      https: true
      validate_certs: false
    register: credentials
  - debug:  var=credentials
  - name: Export Create
    na_ontap_export_policy:
      state: present
      name: volume_policy
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Export Policy Rule Create
    na_ontap_export_policy_rule:
      state: present
      name: volume_policy
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      protocol: cifs
      rule_index: 1
      super_user_security: any
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Mod Default Policy
    na_ontap_export_policy_rule:
      state: present
      name: default
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      protocol: any
      rule_index: 1
      super_user_security: any
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Initialize Housing Crisis
    na_ontap_quota_policy:
      state: present
      vserver: "{{ vserver }}"
      name: s3_policy
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggr_list: "cluster1_01_SSD_1, cluster1_02_SSD_1"
      aggr_list_multiplier: 4
      size: 1
      size_unit: gb
      policy: volume_policy
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      volume_security_style: ntfs
  - name: Generate Spooky Tree
    netapp.ontap.na_ontap_qtree:
      state: present
      name: s3test
      flexvol_name: "{{ vol_name }}"
      export_policy: volume_policy
      security_style: ntfs
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vserver: "{{ vserver }}"
      https: true
      validate_certs: false
  - name: Quantitative Easing
    netapp.ontap.na_ontap_quotas:
      state: present
      volume: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      quota_target: s3test
      set_quota_status: on
      type: tree
      file_limit: 2
      disk_limit: 3
      set_quota_status: True
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
#      policy: s3_policy
      https: true
      validate_certs: false
  - name: Modify single service policy
    netapp.ontap.na_ontap_service_policy:
      state: present
      name: "{{ service_policy_name }}"
      services:
        - data_core
        - data_nfs
        - data_cifs
        - data_s3_server
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      use_rest: always
      https: true
      validate_certs: false
  - name: Create and modify a S3 Group
    netapp.ontap.na_ontap_s3_groups:
      state: present
      name: dev-group
      comment: group for devs
      users:
        - name: user1
      policies:
        - name: FullAccess
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      use_rest: always
      https: true
      validate_certs: false
  - name: Create S3 Bucket
    netapp.ontap.na_ontap_command:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      command: ['object-store-server', 'bucket', 'create', '-type', 'nas', '-bucket', 's3_test', '-nas-path', '/s3_test']
      privilege: 'admin'
      https: true
      validate_certs: false
